Tanzanian Consulate Act, adding two additional ministerial foreign (to tanzania) positions.html
TheSuperGamer20578/sudan-laws pull request #1
Opened 2021-08-31 04:47 UTC by godlyeriss

2021-08-31 05:10 UTC, TheSuperGamer20578 requested changes
Does not state how many people run for each position.

2021-08-31 05:10 UTC, TheSuperGamer20578 commented on Tanzanian Consulate Act, adding two additional ministerial foreign (to tanzania) positions.html
> +    one week at a time up to five times.
Being able to stop the Ministry from voting is probably a bad idea.

2021-08-31 05:11 UTC, godlyeriss commented on Tanzanian Consulate Act, adding two additional ministerial foreign (to tanzania) positions.html
> +    one week at a time up to five times.
one each. it doesnt stop the ministry it just transfers their voting power to the supreme consul

2021-08-31 05:14 UTC, TheSuperGamer20578 commented on Tanzanian Consulate Act, adding two additional ministerial foreign (to tanzania) positions.html
> +    one week at a time up to five times.
If it transfers voting power, the Ministry won't be able to vote.

2021-08-31 05:54 UTC, godlyeriss commented on Tanzanian Consulate Act, adding two additional ministerial foreign (to tanzania) positions.html
> +    one week at a time up to five times.
no it gives the Grand Consul's vote to the Supreme Consul

2021-08-31 05:58 UTC, TheSuperGamer20578 commented on Tanzanian Consulate Act, adding two additional ministerial foreign (to tanzania) positions.html
> +    one week at a time up to five times.
It clearly says "transfer voting power in the ministry to the Supreme Consul", it implies the whole ministry.

2021-08-31 09:06 UTC, godlyeriss commented on Tanzanian Consulate Act, adding two additional ministerial foreign (to tanzania) positions.html
> +    one week at a time up to five times.
oh i meant transfer the grand consul's power

2021-08-31 10:39 UTC, TheSuperGamer20578 commented on Tanzanian Consulate Act; Adding two additional ministerial foreign (to tanzania) positions.html
> +    one week at a time up to five times.
If a term is one month and they can do this for up to a week at a time, wouldn't 5 times mean they can do it for, knger than their term? Or is ommiting per term done on purpose and the position can only ever do it 5 times? 
```suggestion
    one week at a time up to three times each term.
```

2021-08-31 10:43 UTC, TheSuperGamer20578 requested changes

2021-08-31 10:43 UTC, TheSuperGamer20578 commented on Tanzanian Consulate Act; Adding two additional ministerial foreign (to tanzania) positions.html
> +</p>
This does not state when the elections should happen or how long the campeigning period should be.

2021-09-01 01:09 UTC, godlyeriss commented on Tanzanian Consulate Act; Adding two additional ministerial foreign (to tanzania) positions.html
> +    one week at a time up to five times.
yeah do that

2021-09-01 01:42 UTC, TheSuperGamer20578 commented on Tanzanian Consulate Act; Adding two additional ministerial foreign (to tanzania) positions.html
> +</p>
Read Section [2.1](http://emc-sudan.herokuapp.com/laws/Constitution#2.1) of the Constitution for an example.

2021-09-01 01:43 UTC, TheSuperGamer20578 approved these changes

2021-09-01 01:43 UTC, merged